category_corrections = {'alimentacion_conservas': 'alimentacion',
    'alimentacion_legumbres': 'alimentacion', 'bebidas_vinos': 'bebidas',
    'bebidas_zumos_y_nectares': 'bebidas', 'charcuteria_jamon': 'charcuteria',
    'congelados_y_helados_pescado_y_marisco': 'congelados_y_helados',
    'cuidado_del_hogar_cuidado_de_la_ropa': 'cuidado_del_hogar',
    'cuidado_del_hogar_productos_de_limpieza': 'cuidado_del_hogar',
    'cuidado_del_hogar_utensilios_de_limpieza': 'cuidado_del_hogar',
    'cuidado_facial_y_corporal_cuidado_corporal': 'cuidado_facial_y_corporal',
    'cuidado_facial_y_corporal_cuidado_e_higiene_facial': 'cuidado_facial_y_corporal',
    'cuidado_facial_y_corporal_higiene': 'cuidado_facial_y_corporal',
    'cuidado_personal_bano_e_higiene': 'cuidado_personal',
    'cuidado_personal_cuidado_bucal': 'cuidado_personal',
    'cuidado_personal_cuidado_corporal': 'cuidado_personal',
    'cuidado_personal_cuidado_corporal_cuidado_de_manos_y_pies': 'cuidado_personal',
    'cuidado_personal_cuidado_intimo': 'cuidado_personal',
    'desayuno_dulces_y_pan_cafe': 'desayuno_dulces_y_pan',
    'drogueria_y_limpieza_cuidado_ropa': 'drogueria_y_limpieza',
    'drogueria_y_limpieza_limpiadores_para_el_hogar': 'drogueria_y_limpieza',
    'drogueria_y_limpieza_conservacion_alimentos': 'drogueria_y_limpieza',
    'la_despensa_yogures_y_postres': 'la_despensa',
    'lacteos_y_huevos_yogures': 'lacteos_y_huevos',
    'lacteos_y_huevos_yogures_yogur': 'lacteos_y_huevos',
    'mascotas_gatos': 'mascotas',
    'perfumeria_e_higiene_cuidado': 'perfumeria_e_higiene',
    'perfumeria_e_higiene_higiene': 'perfumeria_e_higiene',
    'perfumeria_e_higiene_limpieza_facial': 'perfumeria_e_higiene',
    'productos_frescos_charcuteria': 'productos_frescos',
    'productos_sin_gluten_productos_sin_gluten_productos_sin_gluten': 'productos_sin_gluten',
    'limpieza_y_hogar_cuidado_de_la_ropa': 'limpieza_y_hogar',
    'limpieza_y_hogar_papeleria': 'limpieza_y_hogar',
    'limpieza_y_hogar_productos_para_bano': 'limpieza_y_hogar',
    'limpieza_y_hogar_productos_para_cocina': 'limpieza_y_hogar',
    'limpieza_y_hogar_productos_para_toda_la_casa': 'limpieza_y_hogar',
    'limpieza_y_hogar_utensilios_de_limpieza': 'limpieza_y_hogar',
    'parafarmacia_cuidado_corporal': 'parafarmacia',
    'parafarmacia_cuidado_corporal_cuidado_intimo': 'parafarmacia',
    'parafarmacia_cuidado_de_manos_y_pies': 'parafarmacia',
    'parafarmacia_cuidado_e_higiene': 'parafarmacia',
    'parafarmacia_higiene': 'parafarmacia',
    'perfumeria_e_higiene_cuidado_corporal': 'perfumeria_e_higiene',
    'perfumeria_e_higiene_cuidado_del_cabello': 'perfumeria_e_higiene',
    'perfumeria_e_higiene_cuidado_facial': 'perfumeria_e_higiene',
    'perfumeria_e_higiene_cuidado_manos': 'perfumeria_e_higiene',
    'perfumeria_e_higiene_cuidado_pies': 'perfumeria_e_higiene',
    'perfumeria_e_higiene_cuidado_y_proteccion': 'perfumeria_e_higiene'}

supercategories = {'aceite_especias_y_salsas': 'alimentacion_otros',
    'agua_y_refrescos': 'bebidas', 'al_dia': 'frescos',
    'alimentacion': 'alimentacion_otros', 'aperitivos': 'alimentacion_otros',
    'arroz_legumbres_y_pasta': 'alimentacion_otros',
    'azucar_caramelos_y_chocolate': 'dulce', 'bebe': 'bebe',
    'bebe_alimentacion_infantil': 'bebe', 'bebe_cuidado_del_bebe': 'bebe',
    'bebidas': 'bebidas', 'bodega': 'bebidas',
    'cacao_cafe_e_infusiones': 'bebidas', 'carne': 'carne',
    'carniceria': 'carne', 'cereales_y_galletas': 'dulce',
    'charcuteria': 'carne', 'charcuteria_y_quesos': 'lacteos_y_huevos',
    'charcuteria_y_quesos_al_corte': 'lacteos_y_huevos',
    'congelados': 'congelados', 'congelados_y_helados': 'congelados',
    'conservas_caldos_y_cremas': 'conservas', 'cuidado_del_cabello': 'higiene',
    'cuidado_del_hogar': 'drogueria', 'cuidado_facial_y_corporal': 'higiene',
    'cuidado_personal': 'higiene', 'desayuno_dulces_y_pan': 'panaderia',
    'despensa': 'conservas', 'drogueria_y_limpieza': 'drogueria',
    'dulces_de_navidad': 'panaderia', 'fitoterapia_y_parafarmacia': 'higiene',
    'frescos': 'frescos', 'fruta_y_verdura': 'fruta_y_verdura',
    'frutas': 'fruta_y_verdura',
    'huevos_leche_y_mantequilla': 'lacteos_y_huevos',
    'la_cocina_de_carrefour': 'precocinados', 'la_despensa': 'conservas',
    'lacteos_y_huevos': 'lacteos_y_huevos', 'limpieza_y_hogar': 'drogueria',
    'maquillaje': 'higiene', 'marisco_y_pescado': 'pescado',
    'mascotas': 'mascotas', 'panaderia_bolleria_y_pasteleria': 'panaderia',
    'panaderia_y_pasteleria': 'panaderia', 'parafarmacia': 'higiene',
    'perfumeria_e_higiene': 'higiene', 'pescaderia': 'pescado',
    'pizzas_y_platos_preparados': 'precocinados',
    'platos_preparados': 'precocinados',
    'postres_y_yogures': 'lacteos_y_huevos', 'productos_frescos': 'frescos',
    'productos_frescos_la_cocina_de_carrefour': 'frescos',
    'productos_sin_gluten': 'alimentacion_otros', 'quesos': 'lacteos_y_huevos',
    'quesos_con_denominacion_origen': 'lacteos_y_huevos',
    'soy_solidario': None, 'verduras_y_hortalizas': 'fruta_y_verdura',
    'zumos': 'bebidas', }
